name: Exercise workflow 2
on: [push, workflow_dispatch]
jobs:
  lint:  
    needs: tests  
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nNodeJs
        uses: actions/setup-node@v3 
        with: 
          node-version: 18
      - name: Install depdendencies
        run: npm ci 
      - name: run lint 
        run: npm run lint
  test:  
    needs: tests  
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nNodeJs
        uses: actions/setup-node@v3 
        with: 
          node-version: 18
      - name: Install depdendencies
        run: npm ci 
      - name: Test 
        run: npm test 
  build:  
    needs: tests  
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nNodeJs
        uses: actions/setup-node@v3 
        with: 
          node-version: 18
      - name: Install depdendencies
        run: npm ci 
      - name: Build
        run: npm run build
  Deploy:  
    needs: tests  
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install nNodeJs
        uses: actions/setup-node@v3 
        with: 
          node-version: 18
      - name: Install depdendencies
        run: npm ci 
      - name: Deploy
        run:  echo "Deploying project using different jobs .........."  
     
      