name: Issues workflow
on: issues
jobs: 
  info:
    runs-on: ubuntu-latest
    steps: 
      - name: Output Github context
        run: | 
          echo "Repository ${{ github.repository }}"
          echo "Author ${{ github.repository_owner }}"
          echo "Github context "${{ toJSON(github) }}"
          echo "Event info  "${{ toJSON(github.event) }}"

